name: coverage

on: [push, pull_request]

jobs:

  codecov:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Download Google Test
        run: |
          wget https://github.com/google/googletest/archive/release-1.12.1.tar.gz
          tar xvzf release-1.12.1.tar.gz

      - name: Build and install Google Test
        run: |
          cd googletest-release-1.12.1/
          cmake .
          make
          sudo make install
        
     - uses: actions/checkout@v2
      - name: Compile tests
        working-directory: build
        env:
          CXXFLAGS: "--coverage -fno-inline"
          CXX: g++
        run: |
          cmake -DMUSTACHE_BUILD_TESTS=ON ..
          make -j4
      - name: Run tests
        working-directory: build
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: ctest --timeout 120 -C Debug -j4
      - name: Collect data
        working-directory: build
        run: |
          sudo apt install lcov
          lcov -c -d . -o coverage.info
          lcov -l coverage.info
